export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const AMENITY_REQUEST = "AMENITY_REQUEST";
export const AMENITY_SUCCESS = "AMENITY_SUCCESS"
export const AMENITY_FAIL = "AMENITY_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS";
