export const COMPANY_REQUEST = "COMPANY_REQUEST";
export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const COMPANY_FAIL = "COMPANY_FAIL";

export const COMPANY_ME_REQUEST = "COMPANY_ME_REQUEST";
export const COMPANY_ME_SUCCESS = "COMPANY_ME_SUCCESS";
export const COMPANY_ME_FAIL = "COMPANY_ME_FAIL";

export const COMPANY_DETAIL_REQUEST = "COMPANY_DETAIL_REQUEST";
export const COMPANY_DETAIL_SUCCESS = "COMPANY_DETAIL_SUCCESS";
export const COMPANY_DETAIL_FAIL = "COMPANY_DETAIL_FAIL";


export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAIL = "ADD_COMPANY_FAIL";

export const FAVOURITE_REQUEST = "FAVOURITE_REQUEST";
export const FAVOURITE_SUCCESS = "FAVOURITE_SUCCESS";
export const FAVOURITE_FAIL = "FAVOURITE_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
