export const ListingData = [
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
  {
    businessName: "RVTech",
    location: "Sanjay Nagar, UP",
    phone: "9560988343",
    category: "Software Development",
    type: "Open",
    image: "assets/images/featured-1.jpg",
  },
];
